// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBECkbySupkwO26GRsMsynqrlCfOiSWRSI',
    appId: '1:910629229591:web:38b54414d98c08a3043852',
    messagingSenderId: '910629229591',
    projectId: 'motrocycal',
    authDomain: 'motrocycal.firebaseapp.com',
    databaseURL: 'https://motrocycal-default-rtdb.firebaseio.com',
    storageBucket: 'motrocycal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCByLI4N6S90a46YWqPiEF3AeqMz2l-wS0',
    appId: '1:910629229591:android:7904feb438d2ecf3043852',
    messagingSenderId: '910629229591',
    projectId: 'motrocycal',
    databaseURL: 'https://motrocycal-default-rtdb.firebaseio.com',
    storageBucket: 'motrocycal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxZbMPLFaJ_zuB28J2rNsdtVXqCj4153I',
    appId: '1:910629229591:ios:0ec6e86e287b27b9043852',
    messagingSenderId: '910629229591',
    projectId: 'motrocycal',
    databaseURL: 'https://motrocycal-default-rtdb.firebaseio.com',
    storageBucket: 'motrocycal.appspot.com',
    androidClientId: '910629229591-4okj1i118f3hhumo2l9qcs1b9s6ib363.apps.googleusercontent.com',
    iosClientId: '910629229591-0qk09oohac2av3nlppiiqsh5hv7bkaii.apps.googleusercontent.com',
    iosBundleId: 'com.example.motorcycleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxZbMPLFaJ_zuB28J2rNsdtVXqCj4153I',
    appId: '1:910629229591:ios:b9aaefa9c56d1f0e043852',
    messagingSenderId: '910629229591',
    projectId: 'motrocycal',
    databaseURL: 'https://motrocycal-default-rtdb.firebaseio.com',
    storageBucket: 'motrocycal.appspot.com',
    androidClientId: '910629229591-4okj1i118f3hhumo2l9qcs1b9s6ib363.apps.googleusercontent.com',
    iosClientId: '910629229591-t4fsoa1p1dj58fkpqaifp7oip9dijg66.apps.googleusercontent.com',
    iosBundleId: 'com.example.motorcycleApp.RunnerTests',
  );
}
